print("\033[5;37;40m\n")
print('You find yourself stranded in a rainforest.')
print("Rain is downpouring on you and you need to find shelter.")
print("You find a dark cave that says do not enter.")
print('')
Do_you_enter = (input("Do you enter? "))
if Do_you_enter.lower() == 'yes':
    print('You enter the cave and as you do. ')
    print('An Avalanche appears on top of the cave .')
    print('And closes you inside then you hear a loud roar. ')
    print('')
    deeper = str(input('Go DEEPER or STAY? '))
    if deeper.upper() == 'DEEPER':
        print('You stumble down the cave where you find a fire in the distance.')
        print('You cry for help as you see the fire and a large shadow appears near the fire.')
        print('Then the fire extinguishes in a matter of seconds and you')
        print('hear a deep voice whisper in your ear "run".')
        print('')
        chase= str(input('Do you RUN or STAY? '))
        if chase.upper() == 'RUN':
             print("\033[5;32;40m\n")
             print('You sprint forward away from the voice as you do.')
             print('You reach the tip top of a waterfall tripping over.')
             print('yourself you fall down the waterfall. Into a giant lake in the cave.')
             print('You see a small cave out of the water in the distance and swim to it.')
             print('You live there for the rest of your life. Island ending')
        elif chase.upper() == 'STAY':
             print("\033[3;32;40m\n")
             print('A huge dude lights a match right next to you and he invites you to his campfire.')
             print('You both chill at the fire and eat marshmellows.')
             print('Happy ending.')
    elif deeper.upper() == 'STAY':
        print('You stay waiting as the loud roar nears closer.')
        print('Then literally nothing happens and you all of a sudden fall asleep.')
        print('You wake up in the grass plains with a red and blue door in front of you.')
        REDORBLUE= str(input('Do you enter the RED door or the BLUE door '))
        if REDORBLUE.upper() == 'RED':
             print("\033[5;33;40m\n")
             print('You enter the red door and enter the milky way.')
             print('You start moving at the speed of light through space.')
             print('You endlessly go into space and never stop. Spacespeed ending.')
        elif REDORBLUE.upper() == 'BLUE':
             print("\033[5;31;40m\n")
             print('you fall into a blue abyss as the shade of blue gets darker and darker. And then')
             print('you float motionless in the abyss hearing and seeing nothing but pitch black.')
             print('')
             print('You have met your end...')
elif Do_you_enter.lower() == 'no':
    print('The floor below you starts to shake.')
    print('within a split of second the ground collapses beneath you.')
    print('You pass out and then wake up in a flower bed two paths proceed you.')
    print('')
    path= str(input('Do you take the LEFT path? or the RIGHT path? '))
    if path.upper() == 'LEFT':
        print('You entered down the left path to what looked like')
        print('a narrow stone bridge over a dark bottomless revine.')
        print('You cross the bridge into a large circular stone platform.')
        print('A 6ft long quartz rod and a device made in stone.')
        print('That looks like some sort of gun.')
        print('')
        weaponchoice = str(input('Do you take the GUN or the ROD? '))
        if weaponchoice.upper() == 'ROD':
                print("\033[5;36;47m\n")
                print('The Rod starts glowing and then all of sudden everything is white.')
                print('White ending')
                print('')
        elif weaponchoice.upper() == 'GUN':
                print("\033[1;31;40m\n")
                print('It turns out its just a rock and then you trip and fall into abyss')
                print('You fall into abyss forever. Abyss ending')
                print('')
    elif path.upper() == 'RIGHT':
         print('You take the right path and you find a spiral stone staircase.')
         print('You enter down the staircase as a orange glow leaks from below.')
         print('You find a bridge to a castle surrounded by a sphere of lava.')
         print('You entered through the bridge to the castle and the gate opens.')
         print('The surface around you rumbles a stone fist appears in front of you.')
         print('')
         fist = str(input('Take the fist? (yes/no?) '))
         if fist.lower() == 'yes':
              print("\033[1;32;44m\n")
              print('A giant rock that appears breaking in from the catle in front of you.')
              print('A rock carved into a sculture of dwayne johnson appears and you both fight.')
              print('You come out victorious by punching him with the fist and your teleported home.')
              print('Home ending')
              print('')
         elif fist.lower() == 'no':
              print("\033[1;30;41m\n")
              print('A rock carved like dwayne johnson breaks in from the castle.')
              print('It throws a giant boulder at you and you go flying into a abyss.') 
              print('Death ending')        
else: 
    print("\033[1;30;41m\n")
    print("You think too hard and it causes you to collapse.")
    print("falling into the unknown of the dark bottomless pit.")