print("\033[1;32;40m Bright Green \n")
print ('Please enter the following information:')
print (' ')
First_name = input ('Enter First name: ')
Last_name = input ('Enter Last name: ')
Email_Address = input ('Enter Email Address: ')
Phone_Number = input ('Enter Phone Number: ')
Job_Title = input ('Enter Job Title: ')
ID_Number = input ('Enter ID Number: ')
Hair_Color = input (' Enter Hair Color: ')
Eye_color = input ('Enter Eye Color: ')
print ('The ID Card is')
print ('-------------------------------------')
print(f'{Last_name.capitalize()}, {First_name.capitalize()}')
print(f'Job Title:: {Job_Title.capitalize()}')
print(f'ID: {ID_Number}')
print (' ')
print(f' {Email_Address}')
print(f' {Phone_Number}')
print(f' {Hair_Color}')
print(f' {Eye_color}')
print ('-------------------------------------')
print (' ')
print('Sending information to India... [PLEASE WAIT]')